### ISSUE TITLE
Ambiguous ERROR: Unable to find 'docker'

### ISSUE THREAD

**Issue by VencaCZ** [loherangrin/o3tanks#53]
## Description

When running initial setup it will fail on "chown: invalid user: ‘user:user’"

## OS

My OS is:

- [ Ubuntu 22.04 ] Linux

## Docker

The output of `docker version`: 

```
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3
```

The output of `docker-compose version`:

```
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.6
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
```
o3tanks.sh

```
if ! [ -S "${docker_socket}" ]; then
        docker_socket="/run/docker.sock"

        if ! [ -S "${docker_socket}" ]; then
                throw_error "${MESSAGES_MISSING_DOCKER}"
        fi
fi
```

There should be different message when there is issue with docker_socket and not ERROR: Unable to find 'docker' 
This error will confuse user into thinking that their is problem with their docker installation instead of checking if they have docker running

**Comment by loherangrin** [comment]
Thanks for reporting these errors.

The first issue (`chown: invalid user: ‘user:user’`) is related to an invalid configuration while creating the technical user inside container images. It may happen when the tool is run as a privileged user instead of a standard user, since running as `root` is discouraged and not fully supported by inner dependencies. I will check if the constraint can be relax to support root anyway, or just provide a better error message to explain what is happening.

Just to exclude other possible causes, did you use `sudo` or `root` user to execute it? In that case, you could evaluate to configure your user group to avoid `sudo` (see [https://docs.docker.com/engine/install/linux-postinstall/](Linux post-installation steps) in the official documentation of Docker Engine), or configure your docker installation in rootless mode (see [https://docs.docker.com/engine/security/rootless/](Run the Docker daemon as a non-root user) in the official documentation of Docker Engine).

For the second part of the issue, I agree with you that the message is misleading. I'm going to push a fix to improve it. Thanks!

**Comment by VencaCZ** [comment]
`
Docker Engine 19.03 (or greater), both root and rootless mode are supported. See [official documentation](https://docs.docker.com/get-docker/) for installation details.
`

Both root and rootless modes were supposed to be supported so I tested root mode first. (I used root user not sudo)

**Comment by loherangrin** [comment]
Those modes are related to the Docker Engine, which has to be configured with the two links above. Instead, the tool was designed to work in user-mode without requiring any additional privilege.

However, there are some cases where running as `root` is mandatory. I'm merging an enhancement that should fix the error that you have found, enabling the execution from a privileged user as long as internal dependencies support it.
