### ISSUE TITLE
Python not found while creating project

### ISSUE THREAD

**Issue by VencaCZ** [loherangrin/o3tanks#57]
WARNING: [Running in DEV_MODE]
WARNING: [Running in DEV_MODE]
Python not found in /home/user/o3de/engine/python
Try running /home/user/o3de/engine/python/get_python.sh first.
ERROR: An unexpected error could be occurred while creating the project files
ERROR: Container from image 'o3tanks-builder:development_ubuntu_22.04' failed with error code: 1

Mu username is not **user** so probably script is not getting username properly

**Comment by loherangrin** [comment]
If you are running inside containers (the default mode on Linux), it is correct that is returning `user` instead of your host username. In fact, this is the technical user that is running inside containers, so that generated images are more portable and not related to the building machine.

The error is thrown by O3DE, not the tool itself. There could be many reasons since it is happening, so can you provide more context about which commands you used, the current status of your engine installation, etc.? For instance:
1. Is the engine installation completed successfully? You can check using `o3tanks list` and see if you have a version with SOURCE ~8GB and SDK ~27GB
2. Which engine version are you using? Since the `development` branch of O3DE might have building issues, did you try the stable version (2305.0)?

**Comment by VencaCZ** [comment]
`o3tanks list`

template: :1:3: executing "" at <.SecurityOptions>: reflect: indirection through nil pointer to embedded struct field Info
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%22LOCALE%22%3A%22C.UTF-8%22%2C%22OS_IMAGE%22%3A%22ubuntu%3A22.04%22%2C%22OS_NAME%22%3A%22ubuntu%22%2C%22OS_VERSION%22%3A%2222.04%22%2C%22USER_GID%22%3A%221001%22%2C%22USER_GROUP%22%3A%22user%22%2C%22USER_NAME%22%3A%22user%22%2C%22USER_UID%22%3A%221001%22%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile.linux&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=o3tanks-cli%3Adevelopment_ubuntu_22.04&target=cli_dev&ulimits=null&version=1": dial unix /var/run/docker.sock: connect: permission denied

`sudo o3tanks list`

Sorry, user test is not allowed to execute '/usr/local/bin/o3tanks list' as root on venca-doma.

Which engine version are you using?

I have tried development, main and 2305 just in case there would be difference, but there was nothing

**Comment by VencaCZ** [comment]
`$ sudo o3tanks list
   
WARNING: [Running in DEV_MODE]
ENGINES                TOTAL        SOURCE     BUILD       SDK         BUILD WORKFLOW         DEBUG     PROFILE    RELEASE  
main                   5.4 GB       5.4 GB     0.0 B      0.0 B       Project / Source         Any        Any        Any    
development            5.3 GB       5.3 GB     0.0 B      0.0 B       Project / Source         Any        Any        Any `

**Comment by loherangrin** [comment]
Sorry, I thought that you already passed that issue since you are at project creation and it was only for reporting.
I've posted the correct command, try to install again the engine (it may take a while to build) and check that the SDK column becomes not-empty

**Comment by VencaCZ** [comment]
Everything worked now after and I was able to create, build and run project.
